spring:
  datasource:
    username: sa
    url: jdbc:h2:file:./src/main/resources/db/apidb
    driverClassName: org.h2.Driver
    password: sa2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /swagger-ui.html